        ;; PIO registers defines - OUTDATED & NON USED.

	;; Control register (normal mode):
PIO_NORMAL_CONTROL_MODE:	equ 0x80 ; Mandatory if we use the normal control mode
	
PIO_PORT_C_LOWER_AS_INPUT:	equ 0x01
PIO_PORT_C_LOWER_AS_OUTPUT:	equ 0x00
PIO_PORT_C_UPPER_AS_INPUT:	equ 0x08
PIO_PORT_C_UPPER_AS_OUTPUT:	equ 0x00

PIO_PORT_B_AS_INPUT:		equ 0x02
PIO_PORT_B_AS_OUTPUT:		equ 0x00
PIO_GROUP_B_MODE_0:		equ 0x00
PIO_GROUP_B_MODE_1:		equ 0x04

PIO_PORT_A_AS_INPUT:		equ 0x10
PIO_PORT_A_AS_OUTPUT:		equ 0x00
PIO_GROUP_A_MODE_0:		equ 0x00
PIO_GROUP_A_MODE_1:		equ 0x20
PIO_GROUP_A_MODE_2:		equ 0x40

	;; Control register (Set flag mode)
PIO_BIT_SET_MODE:		equ 0x00 ; Independant port C Bit set
	
PIO_BIT_SET:			equ 0x01
PIO_BIT_RESET:			equ 0x00

PIO_BIT_0:			equ 0x02
PIO_BIT_1:			equ 0x04
PIO_BIT_2:			equ 0x06
PIO_BIT_3:			equ 0x08
PIO_BIT_4:			equ 0x0A
PIO_BIT_5:			equ 0x0C

	;; Misc
PIO_CONFIG_PORT_A_OUTPUT_PORT_C_OUTPUT:	equ  PIO_NORMAL_CONTROL_MODE | PIO_GROUP_A_MODE_0 | PIO_GROUP_B_MODE_0 | PIO_PORT_A_AS_OUTPUT | PIO_PORT_B_AS_INPUT | PIO_PORT_C_LOWER_AS_OUTPUT | PIO_PORT_C_UPPER_AS_OUTPUT

PIO_CONFIG_PORT_A_INPUT_PORT_C_OUTPUT:	equ  PIO_NORMAL_CONTROL_MODE | PIO_GROUP_A_MODE_0 | PIO_GROUP_B_MODE_0 | PIO_PORT_A_AS_INPUT | PIO_PORT_B_AS_INPUT | PIO_PORT_C_LOWER_AS_OUTPUT | PIO_PORT_C_UPPER_AS_OUTPUT
